#!/bin/bash
#####( ᵔ︡ ͜ʖ ᵔ︠ ) *Before executing bash script you may create a tmp folder and move bash script in the tmp folder for execution. EX, mkdir tmp 
#########ʕ 👁️ ͜ʖ 👁️ ʔ *Please visit tuterial web1=http://www.mdtutorials.com/gmx/lysozyme/08_MD.html and web2=https://www.gromacs.org/Downloads. The gmx commands are copied and modified from there. 
#########ʕ 👁️ ͜ʖ 👁️ ʔ *Please download from my driver to run the calculation. You will have all *.mdp parameter files with the proper file names. Regarding downloading please send 
#########ʕ 👁️  ͜ʖ 👁️  ʔ    me a message(rishat.dilmurat@gmail.com) or I may put it somewhere convenient place. You may also download a relatively different version from the first tutorial website. 
#########ʕ 👁️  ͜ʖ 👁️  ʔ     After downloading, please modify both file names and parameters for water molecules. 
#########ʕ 👁️ ͜ʖ 👁️  ʔ *finally execute the bash file. ./create_water.sh


# you may always change the size of the box(as example here is 3nm) and number of molecules in the box.
# you may change water to the other solvent

#++++++.1.++++++ Create water n the box #
#box with number of water molecules inside the box(number of the molecules are automatically created)#
#3-point model (e.g. SPC, SPC/E or TIP3P) it will work with specify -cs spc216.gro which
#will take this file from the gromacs/share/top

boxa=3;boxb=3;boxc=3
gmx solvate -cs spc216.gro -box $boxa $boxb $boxc -o water

# you may insert the number of molecules (as you want) in the given box as following instructions.
# For that please create an example.gro file. The example.gro file should be as follows.
# please just copy-paste the following example and save as example.gro.
# #title  (Generated by gmx solvate)
# #number of atom (1)
# GMX coordinates(nm) for .gro file
# size of the box (nm)

#****************************for instance*******************************************
#echo Generated by gmx solvate                  >  example.gro
#echo 3                                         >> example.gro
#echo  1SOL     OW 1006   1.300   0.453   2.553 >> example.gro
#echo  1SOL    HW1 1007   1.241   0.533   2.557 >> example.gro
#echo  1SOL    HW2 1008   1.315   0.418   2.646 >> example.gro
#echo  3.00000   3.00000   3.00000              >> example.gro
#************************************************************************************
#number of water molecules mol=200
#gmx insert-molecules -ci example.gro -nmol $mol -box $boxa $boxb $boxc -o ${mol}_box.gro -seed 100

#++++++.1 continue.++++++ Create topology file for water molecules 'topol.top'#
# echo 15 choose option 15 with force field 'OPLS-AA/L all-atom force field (2001 aminoacid dihedrals)'
# You may immediately see the difference between water.gro and water.out.gro files. 

echo 15 |  gmx pdb2gmx -f water.gro -o water.out.gro -water spce

#_________________________________REAL_BUSINESS=MD_calculation_____________________________________________#
#++++++.2.++++++ Energy Minimization#
# we have water.out.gro and topol.top, find *.mdp parameter file on web http://www.mdtutorials.com/gmx/lysozyme/05_EM.html
# please read Gromacs manual booklet from Gromacs web

mkdir minEn
cp water.out.gro miniEn.mdp topol.top minEn
cd minEn

gmx grompp -f miniEn.mdp -c water.out.gro -p topol.top -o miniEn.tpr
gmx mdrun -v -deffnm miniEn

cd ..

#++++++.2.1++++++ nvt calculation#
# find nvt.mdp file in the $web1 or download from the drive. plot temperature_VS_time from temperature.xvg 

mkdir nvt
cp nvt.mdp nvt
cp minEn/miniEn.gro nvt/water.minEn.gro  
cp minEn/topol.top nvt/ 

cd nvt/
 
gmx grompp -f nvt.mdp -c water.minEn.gro -r water.minEn.gro -p topol.top -o water_nvt.tpr
gmx mdrun -deffnm water_nvt

echo 9 | gmx energy -f water_nvt.edr -o temperature.xvg

cd ..

#++++++.2.1++++++ npt calculation#
# find npt.mdp file in the $web1 or download from the drive. plot pressure_VS_time from pressure.xvg 

mkdir npt
cp topol.top npt.mdp  npt/
cp nvt/water_nvt.gro npt/
cp nvt/water_nvt.cpt npt/

cd npt/

gmx grompp -f npt.mdp -c water_nvt.gro -r water_nvt.gro -t water_nvt.cpt -p topol.top -o water_npt.tpr
gmx mdrun -deffnm water_npt

echo 11 | gmx energy -f water_npt.edr -o pressure.xvg

cd ..


#++++++.2.3++++++ Production_MD calculation#
#gmx grompp -f prdc.mdp -c water_npt.gro -t water_npt.cpt -p topol.top -o water_prdc.tpr
#gmx mdrun -deffnm water_prdc


mkdir prdc/
cp topol.top prdc.mdp prdc/
cp npt/water_npt.gro   prdc/
cp npt/water_npt.cpt   prdc/

cd prdc/

gmx grompp -f prdc.mdp -c water_npt.gro -t water_npt.cpt -p topol.top -o water_prdc.tpr
gmx mdrun -deffnm water_prdc

cd ..



#gmx trjconv -f water_prdc.trr -s water_prdc.tpr -n water_prdc.ndx -pbc mol -vel -b 60 -e 100 -center -o water_prdc_99.gro
#gmx trjconv -f water_prdc.trr -s water_prdc.tpr -n water_prdc.ndx -pbc mol -vel -sep -nzero 3 -b 60 -e 100 -center -o water_prdc_.gro(-nzero 3 3 digit )
# -shift 2 2 2 
#gmx trjconv -f water_prdc.trr -s water_prdc.tpr -n water_prdc.ndx -pbc mol -center  -vel -sep -nzero 3 -b 500 -e 1000 -tu ps -o water_prdc_.gro
#gmx trjconv -f water_prdc.trr -s water_prdc.tpr -n water_prdc.ndx -pbc mol -center  -vel -sep -nzero 3 -b 500 -e 1000 -tu ps -o water_prdc_.gro
